# Generated by Django 5.0.4 on 2024-05-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_appointment_patient_delete_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='user',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
